import type { ArticleOriginalContent } from "../types";

const nce4L40: ArticleOriginalContent = {
    paragraphs: [
      [
{ text: "Waves are the children of the struggle between ocean and atmosphere, the ongoing signatures of infinity.", translation: "", predicates: [], clauseIntroducers: [], auxiliaries: [], inlineAnnotations: [] },
{ text: "Rays from the sun excite and energize the atmosphere of the earth, awakening it to flow, to movement, to rhythm, to life.", translation: "", predicates: [], clauseIntroducers: [], auxiliaries: [], inlineAnnotations: [] },
{ text: "The wind then speaks the message of the sun to the sea and the sea transmits it on through waves — an ancient, exquisite, powerful message.", translation: "", predicates: [], clauseIntroducers: [], auxiliaries: [], inlineAnnotations: [] },
{ text: "These ocean waves are among the earth's most complicated natural phenomena.", translation: "", predicates: [], clauseIntroducers: [], auxiliaries: [], inlineAnnotations: [] },
{ text: "The basic features include a crest (the highest point of the wave), a trough (the lowest point), a height (the vertical distance from the trough to the crest), a wave length (the horizontal distance between two wave crests), and a period (which is the time it takes a wave crest to travel one wave length).", translation: "", predicates: [], clauseIntroducers: [], auxiliaries: [], inlineAnnotations: [] },
{ text: "Although an ocean wave gives the impression of a wall of water moving in your direction, in actuality waves move through the water leaving the water about where it was.", translation: "", predicates: [], clauseIntroducers: [], auxiliaries: [], inlineAnnotations: [] },
{ text: "If the water was moving with the wave, the ocean and everything on it would be racing in to the shore with obviously catastrophic results.", translation: "", predicates: [], clauseIntroducers: [], auxiliaries: [], inlineAnnotations: [] },
{ text: "An ocean wave passing through deep water causes a particle on the surface to move in a roughly circular orbit, drawing the particle first towards the advancing wave, then up into the wave, then forward with it and then — as the wave leaves the particles behind — back to its starting point again.", translation: "", predicates: [], clauseIntroducers: [], auxiliaries: [], inlineAnnotations: [] },
{ text: "From both maturity to death, a wave is subject to the same laws as any other 'living' thing.", translation: "", predicates: [], clauseIntroducers: [], auxiliaries: [], inlineAnnotations: [] },
{ text: "For a time it assumes a miraculous individuality that, in the end, is reabsorbed into the great ocean of life.", translation: "", predicates: [], clauseIntroducers: [], auxiliaries: [], inlineAnnotations: [] },
{ text: "The undulating waves of the open sea are generated by three natural causes: wind, earth movements or tremors, and the gravitational pull of the moon and the sun.", translation: "", predicates: [], clauseIntroducers: [], auxiliaries: [], inlineAnnotations: [] },
{ text: "Once waves have been generated, gravity is the force that drives them in a continual attempt to restore the ocean surface to a flat plain.", translation: "", predicates: [], clauseIntroducers: [], auxiliaries: [], inlineAnnotations: [] }
      ]
    ],
  };

export default nce4L40;
