export interface WordEntry {
  /** 单词本身 */
  word: string
  /** 音标（IPA） */
  phonetic: string
  /** 词性 */
  pos: string
  /** 中文释义 */
  meaning: string
}

/**
 * 内置词库：高频基础英语词汇（音标 / 词性 / 中文释义）
 * 供听写打字练习使用
 */
export const WORDS: WordEntry[] = [
  // ── 食物 ──
  { word: "apple", phonetic: "/ˈæpl/", pos: "n.", meaning: "苹果" },
  { word: "banana", phonetic: "/bəˈnɑːnə/", pos: "n.", meaning: "香蕉" },
  { word: "bread", phonetic: "/bred/", pos: "n.", meaning: "面包" },
  { word: "milk", phonetic: "/mɪlk/", pos: "n.", meaning: "牛奶" },
  { word: "water", phonetic: "/ˈwɔːtə(r)/", pos: "n.", meaning: "水" },
  { word: "rice", phonetic: "/raɪs/", pos: "n.", meaning: "米饭；大米" },
  { word: "egg", phonetic: "/eɡ/", pos: "n.", meaning: "鸡蛋" },
  { word: "meat", phonetic: "/miːt/", pos: "n.", meaning: "肉" },
  { word: "vegetable", phonetic: "/ˈvedʒtəbl/", pos: "n.", meaning: "蔬菜" },
  { word: "fruit", phonetic: "/fruːt/", pos: "n.", meaning: "水果" },
  { word: "breakfast", phonetic: "/ˈbrekfəst/", pos: "n.", meaning: "早餐" },
  { word: "dinner", phonetic: "/ˈdɪnə(r)/", pos: "n.", meaning: "晚餐" },
  { word: "chicken", phonetic: "/ˈtʃɪkɪn/", pos: "n.", meaning: "鸡肉；鸡" },
  { word: "cake", phonetic: "/keɪk/", pos: "n.", meaning: "蛋糕" },
  { word: "coffee", phonetic: "/ˈkɒfi/", pos: "n.", meaning: "咖啡" },
  { word: "tea", phonetic: "/tiː/", pos: "n.", meaning: "茶" },
  { word: "sugar", phonetic: "/ˈʃʊɡə(r)/", pos: "n.", meaning: "糖" },
  { word: "salt", phonetic: "/sɔːlt/", pos: "n.", meaning: "盐" },
  { word: "juice", phonetic: "/dʒuːs/", pos: "n.", meaning: "果汁" },
  { word: "orange", phonetic: "/ˈɒrɪndʒ/", pos: "n./adj.", meaning: "橙子；橙色的" },

  // ── 动物 ──
  { word: "cat", phonetic: "/kæt/", pos: "n.", meaning: "猫" },
  { word: "dog", phonetic: "/dɒɡ/", pos: "n.", meaning: "狗" },
  { word: "elephant", phonetic: "/ˈelɪfənt/", pos: "n.", meaning: "大象" },
  { word: "fish", phonetic: "/fɪʃ/", pos: "n.", meaning: "鱼" },
  { word: "grape", phonetic: "/ɡreɪp/", pos: "n.", meaning: "葡萄" },
  { word: "horse", phonetic: "/hɔːs/", pos: "n.", meaning: "马" },
  { word: "tiger", phonetic: "/ˈtaɪɡə(r)/", pos: "n.", meaning: "老虎" },
  { word: "monkey", phonetic: "/ˈmʌŋki/", pos: "n.", meaning: "猴子" },
  { word: "bird", phonetic: "/bɜːd/", pos: "n.", meaning: "鸟" },
  { word: "lion", phonetic: "/ˈlaɪən/", pos: "n.", meaning: "狮子" },
  { word: "rabbit", phonetic: "/ˈræbɪt/", pos: "n.", meaning: "兔子" },
  { word: "panda", phonetic: "/ˈpændə/", pos: "n.", meaning: "熊猫" },
  { word: "dolphin", phonetic: "/ˈdɒlfɪn/", pos: "n.", meaning: "海豚" },

  // ── 身体 ──
  { word: "head", phonetic: "/hed/", pos: "n.", meaning: "头" },
  { word: "hand", phonetic: "/hænd/", pos: "n.", meaning: "手" },
  { word: "foot", phonetic: "/fʊt/", pos: "n.", meaning: "脚" },
  { word: "eye", phonetic: "/aɪ/", pos: "n.", meaning: "眼睛" },
  { word: "ear", phonetic: "/ɪə(r)/", pos: "n.", meaning: "耳朵" },
  { word: "nose", phonetic: "/nəʊz/", pos: "n.", meaning: "鼻子" },
  { word: "mouth", phonetic: "/maʊθ/", pos: "n.", meaning: "嘴" },
  { word: "heart", phonetic: "/hɑːt/", pos: "n.", meaning: "心脏；内心" },
  { word: "finger", phonetic: "/ˈfɪŋɡə(r)/", pos: "n.", meaning: "手指" },
  { word: "shoulder", phonetic: "/ˈʃəʊldə(r)/", pos: "n.", meaning: "肩膀" },

  // ── 人物 ──
  { word: "father", phonetic: "/ˈfɑːðə(r)/", pos: "n.", meaning: "父亲" },
  { word: "mother", phonetic: "/ˈmʌðə(r)/", pos: "n.", meaning: "母亲" },
  { word: "brother", phonetic: "/ˈbrʌðə(r)/", pos: "n.", meaning: "兄弟" },
  { word: "sister", phonetic: "/ˈsɪstə(r)/", pos: "n.", meaning: "姐妹" },
  { word: "friend", phonetic: "/frend/", pos: "n.", meaning: "朋友" },
  { word: "teacher", phonetic: "/ˈtiːtʃə(r)/", pos: "n.", meaning: "教师" },
  { word: "doctor", phonetic: "/ˈdɒktə(r)/", pos: "n.", meaning: "医生" },
  { word: "student", phonetic: "/ˈstjuːdnt/", pos: "n.", meaning: "学生" },
  { word: "people", phonetic: "/ˈpiːpl/", pos: "n.", meaning: "人们" },
  { word: "child", phonetic: "/tʃaɪld/", pos: "n.", meaning: "孩子" },
  { word: "woman", phonetic: "/ˈwʊmən/", pos: "n.", meaning: "女人" },
  { word: "man", phonetic: "/mæn/", pos: "n.", meaning: "男人" },
  { word: "baby", phonetic: "/ˈbeɪbi/", pos: "n.", meaning: "婴儿" },

  // ── 学校 ──
  { word: "school", phonetic: "/skuːl/", pos: "n.", meaning: "学校" },
  { word: "book", phonetic: "/bʊk/", pos: "n.", meaning: "书" },
  { word: "pen", phonetic: "/pen/", pos: "n.", meaning: "钢笔" },
  { word: "pencil", phonetic: "/ˈpensl/", pos: "n.", meaning: "铅笔" },
  { word: "paper", phonetic: "/ˈpeɪpə(r)/", pos: "n.", meaning: "纸；论文" },
  { word: "lesson", phonetic: "/ˈlesn/", pos: "n.", meaning: "课程；教训" },
  { word: "homework", phonetic: "/ˈhəʊmwɜːk/", pos: "n.", meaning: "家庭作业" },
  { word: "question", phonetic: "/ˈkwestʃən/", pos: "n.", meaning: "问题" },
  { word: "answer", phonetic: "/ˈɑːnsə(r)/", pos: "n./v.", meaning: "答案；回答" },
  { word: "word", phonetic: "/wɜːd/", pos: "n.", meaning: "单词" },

  // ── 自然与地点 ──
  { word: "sun", phonetic: "/sʌn/", pos: "n.", meaning: "太阳" },
  { word: "moon", phonetic: "/muːn/", pos: "n.", meaning: "月亮" },
  { word: "star", phonetic: "/stɑː(r)/", pos: "n.", meaning: "星星；明星" },
  { word: "tree", phonetic: "/triː/", pos: "n.", meaning: "树" },
  { word: "flower", phonetic: "/ˈflaʊə(r)/", pos: "n.", meaning: "花" },
  { word: "river", phonetic: "/ˈrɪvə(r)/", pos: "n.", meaning: "河流" },
  { word: "mountain", phonetic: "/ˈmaʊntən/", pos: "n.", meaning: "山" },
  { word: "sea", phonetic: "/siː/", pos: "n.", meaning: "海" },
  { word: "rain", phonetic: "/reɪn/", pos: "n./v.", meaning: "雨；下雨" },
  { word: "snow", phonetic: "/snəʊ/", pos: "n./v.", meaning: "雪；下雪" },
  { word: "wind", phonetic: "/wɪnd/", pos: "n.", meaning: "风" },
  { word: "weather", phonetic: "/ˈweðə(r)/", pos: "n.", meaning: "天气" },
  { word: "city", phonetic: "/ˈsɪti/", pos: "n.", meaning: "城市" },
  { word: "street", phonetic: "/striːt/", pos: "n.", meaning: "街道" },
  { word: "house", phonetic: "/haʊs/", pos: "n.", meaning: "房子" },
  { word: "garden", phonetic: "/ˈɡɑːdn/", pos: "n.", meaning: "花园" },
  { word: "room", phonetic: "/ruːm/", pos: "n.", meaning: "房间" },
  { word: "door", phonetic: "/dɔː(r)/", pos: "n.", meaning: "门" },
  { word: "window", phonetic: "/ˈwɪndəʊ/", pos: "n.", meaning: "窗户" },
  { word: "table", phonetic: "/ˈteɪbl/", pos: "n.", meaning: "桌子；表格" },
  { word: "chair", phonetic: "/tʃeə(r)/", pos: "n.", meaning: "椅子" },
  { word: "bed", phonetic: "/bed/", pos: "n.", meaning: "床" },
  { word: "park", phonetic: "/pɑːk/", pos: "n.", meaning: "公园" },

  // ── 服饰 ──
  { word: "shirt", phonetic: "/ʃɜːt/", pos: "n.", meaning: "衬衫" },
  { word: "dress", phonetic: "/dres/", pos: "n./v.", meaning: "连衣裙；穿衣服" },
  { word: "shoes", phonetic: "/ʃuːz/", pos: "n.", meaning: "鞋子" },
  { word: "hat", phonetic: "/hæt/", pos: "n.", meaning: "帽子" },
  { word: "coat", phonetic: "/kəʊt/", pos: "n.", meaning: "外套" },
  { word: "trousers", phonetic: "/ˈtraʊzəz/", pos: "n.", meaning: "裤子" },

  // ── 时间 ──
  { word: "morning", phonetic: "/ˈmɔːnɪŋ/", pos: "n.", meaning: "早晨" },
  { word: "afternoon", phonetic: "/ˌɑːftəˈnuːn/", pos: "n.", meaning: "下午" },
  { word: "evening", phonetic: "/ˈiːvnɪŋ/", pos: "n.", meaning: "傍晚" },
  { word: "night", phonetic: "/naɪt/", pos: "n.", meaning: "夜晚" },
  { word: "today", phonetic: "/təˈdeɪ/", pos: "n./adv.", meaning: "今天" },
  { word: "tomorrow", phonetic: "/təˈmɒrəʊ/", pos: "n./adv.", meaning: "明天" },
  { word: "yesterday", phonetic: "/ˈjestədeɪ/", pos: "n./adv.", meaning: "昨天" },
  { word: "week", phonetic: "/wiːk/", pos: "n.", meaning: "星期；周" },
  { word: "month", phonetic: "/mʌnθ/", pos: "n.", meaning: "月份" },
  { word: "year", phonetic: "/jɪə(r)/", pos: "n.", meaning: "年" },
  { word: "hour", phonetic: "/ˈaʊə(r)/", pos: "n.", meaning: "小时" },
  { word: "minute", phonetic: "/ˈmɪnɪt/", pos: "n.", meaning: "分钟" },
  { word: "time", phonetic: "/taɪm/", pos: "n.", meaning: "时间；次数" },
  { word: "second", phonetic: "/ˈsekənd/", pos: "n.", meaning: "秒；第二" },

  // ── 动词 ──
  { word: "run", phonetic: "/rʌn/", pos: "v.", meaning: "跑" },
  { word: "walk", phonetic: "/wɔːk/", pos: "v.", meaning: "走；散步" },
  { word: "swim", phonetic: "/swɪm/", pos: "v.", meaning: "游泳" },
  { word: "jump", phonetic: "/dʒʌmp/", pos: "v.", meaning: "跳" },
  { word: "read", phonetic: "/riːd/", pos: "v.", meaning: "阅读" },
  { word: "write", phonetic: "/raɪt/", pos: "v.", meaning: "写" },
  { word: "listen", phonetic: "/ˈlɪsn/", pos: "v.", meaning: "听" },
  { word: "speak", phonetic: "/spiːk/", pos: "v.", meaning: "说；讲" },
  { word: "learn", phonetic: "/lɜːn/", pos: "v.", meaning: "学习" },
  { word: "teach", phonetic: "/tiːtʃ/", pos: "v.", meaning: "教" },
  { word: "study", phonetic: "/ˈstʌdi/", pos: "v./n.", meaning: "学习；研究" },
  { word: "work", phonetic: "/wɜːk/", pos: "v./n.", meaning: "工作" },
  { word: "play", phonetic: "/pleɪ/", pos: "v.", meaning: "玩；演奏" },
  { word: "sing", phonetic: "/sɪŋ/", pos: "v.", meaning: "唱歌" },
  { word: "dance", phonetic: "/dɑːns/", pos: "v./n.", meaning: "跳舞；舞蹈" },
  { word: "eat", phonetic: "/iːt/", pos: "v.", meaning: "吃" },
  { word: "drink", phonetic: "/drɪŋk/", pos: "v./n.", meaning: "喝；饮料" },
  { word: "sleep", phonetic: "/sliːp/", pos: "v./n.", meaning: "睡觉" },
  { word: "see", phonetic: "/siː/", pos: "v.", meaning: "看见" },
  { word: "watch", phonetic: "/wɒtʃ/", pos: "v.", meaning: "观看" },
  { word: "think", phonetic: "/θɪŋk/", pos: "v.", meaning: "思考；认为" },
  { word: "know", phonetic: "/nəʊ/", pos: "v.", meaning: "知道" },
  { word: "want", phonetic: "/wɒnt/", pos: "v.", meaning: "想要" },
  { word: "need", phonetic: "/niːd/", pos: "v./n.", meaning: "需要" },
  { word: "help", phonetic: "/help/", pos: "v./n.", meaning: "帮助" },
  { word: "love", phonetic: "/lʌv/", pos: "v./n.", meaning: "爱" },
  { word: "like", phonetic: "/laɪk/", pos: "v.", meaning: "喜欢" },
  { word: "make", phonetic: "/meɪk/", pos: "v.", meaning: "制作；做" },
  { word: "take", phonetic: "/teɪk/", pos: "v.", meaning: "拿；带走" },
  { word: "give", phonetic: "/ɡɪv/", pos: "v.", meaning: "给" },
  { word: "come", phonetic: "/kʌm/", pos: "v.", meaning: "来" },
  { word: "go", phonetic: "/ɡəʊ/", pos: "v.", meaning: "去" },
  { word: "find", phonetic: "/faɪnd/", pos: "v.", meaning: "找到" },
  { word: "buy", phonetic: "/baɪ/", pos: "v.", meaning: "买" },
  { word: "sell", phonetic: "/sel/", pos: "v.", meaning: "卖" },
  { word: "open", phonetic: "/ˈəʊpən/", pos: "v./adj.", meaning: "打开；开着的" },
  { word: "close", phonetic: "/kləʊz/", pos: "v.", meaning: "关闭" },
  { word: "start", phonetic: "/stɑːt/", pos: "v./n.", meaning: "开始" },
  { word: "finish", phonetic: "/ˈfɪnɪʃ/", pos: "v.", meaning: "完成" },
  { word: "remember", phonetic: "/rɪˈmembə(r)/", pos: "v.", meaning: "记住" },
  { word: "forget", phonetic: "/fəˈɡet/", pos: "v.", meaning: "忘记" },
  { word: "welcome", phonetic: "/ˈwelkəm/", pos: "v./n.", meaning: "欢迎" },

  // ── 形容词 ──
  { word: "good", phonetic: "/ɡʊd/", pos: "adj.", meaning: "好的" },
  { word: "bad", phonetic: "/bæd/", pos: "adj.", meaning: "坏的" },
  { word: "big", phonetic: "/bɪɡ/", pos: "adj.", meaning: "大的" },
  { word: "small", phonetic: "/smɔːl/", pos: "adj.", meaning: "小的" },
  { word: "long", phonetic: "/lɒŋ/", pos: "adj.", meaning: "长的" },
  { word: "short", phonetic: "/ʃɔːt/", pos: "adj.", meaning: "短的；矮的" },
  { word: "tall", phonetic: "/tɔːl/", pos: "adj.", meaning: "高的" },
  { word: "beautiful", phonetic: "/ˈbjuːtɪfl/", pos: "adj.", meaning: "美丽的" },
  { word: "happy", phonetic: "/ˈhæpi/", pos: "adj.", meaning: "快乐的" },
  { word: "sad", phonetic: "/sæd/", pos: "adj.", meaning: "悲伤的" },
  { word: "hot", phonetic: "/hɒt/", pos: "adj.", meaning: "热的" },
  { word: "cold", phonetic: "/kəʊld/", pos: "adj.", meaning: "冷的" },
  { word: "new", phonetic: "/njuː/", pos: "adj.", meaning: "新的" },
  { word: "old", phonetic: "/əʊld/", pos: "adj.", meaning: "旧的；老的" },
  { word: "young", phonetic: "/jʌŋ/", pos: "adj.", meaning: "年轻的" },
  { word: "fast", phonetic: "/fɑːst/", pos: "adj./adv.", meaning: "快的；快速地" },
  { word: "slow", phonetic: "/sləʊ/", pos: "adj.", meaning: "慢的" },
  { word: "easy", phonetic: "/ˈiːzi/", pos: "adj.", meaning: "容易的" },
  { word: "difficult", phonetic: "/ˈdɪfɪkəlt/", pos: "adj.", meaning: "困难的" },
  { word: "interesting", phonetic: "/ˈɪntrəstɪŋ/", pos: "adj.", meaning: "有趣的" },
  { word: "important", phonetic: "/ɪmˈpɔːtnt/", pos: "adj.", meaning: "重要的" },
  { word: "busy", phonetic: "/ˈbɪzi/", pos: "adj.", meaning: "忙碌的" },
  { word: "tired", phonetic: "/ˈtaɪəd/", pos: "adj.", meaning: "疲惫的" },
  { word: "hungry", phonetic: "/ˈhʌŋɡri/", pos: "adj.", meaning: "饥饿的" },
  { word: "thirsty", phonetic: "/ˈθɜːsti/", pos: "adj.", meaning: "口渴的" },
  { word: "quiet", phonetic: "/ˈkwaɪət/", pos: "adj.", meaning: "安静的" },
  { word: "noisy", phonetic: "/ˈnɔɪzi/", pos: "adj.", meaning: "吵闹的" },
  { word: "clean", phonetic: "/kliːn/", pos: "adj./v.", meaning: "干净的；清洁" },
  { word: "dirty", phonetic: "/ˈdɜːti/", pos: "adj.", meaning: "肮脏的" },
  { word: "strong", phonetic: "/strɒŋ/", pos: "adj.", meaning: "强壮的" },
  { word: "weak", phonetic: "/wiːk/", pos: "adj.", meaning: "虚弱的" },
  { word: "rich", phonetic: "/rɪtʃ/", pos: "adj.", meaning: "富有的" },
  { word: "poor", phonetic: "/pʊə(r)/", pos: "adj.", meaning: "贫穷的" },
  { word: "kind", phonetic: "/kaɪnd/", pos: "adj./n.", meaning: "友善的；种类" },
  { word: "clever", phonetic: "/ˈklevə(r)/", pos: "adj.", meaning: "聪明的" },
  { word: "funny", phonetic: "/ˈfʌni/", pos: "adj.", meaning: "滑稽的" },
  { word: "early", phonetic: "/ˈɜːli/", pos: "adj./adv.", meaning: "早的；提前" },
  { word: "late", phonetic: "/leɪt/", pos: "adj./adv.", meaning: "迟的；晚" },
  { word: "right", phonetic: "/raɪt/", pos: "adj./n.", meaning: "正确的；右边" },
  { word: "wrong", phonetic: "/rɒŋ/", pos: "adj.", meaning: "错误的" },
  { word: "free", phonetic: "/friː/", pos: "adj.", meaning: "自由的；免费的" },
  { word: "different", phonetic: "/ˈdɪfrənt/", pos: "adj.", meaning: "不同的" },
  { word: "same", phonetic: "/seɪm/", pos: "adj.", meaning: "相同的" },
  { word: "great", phonetic: "/ɡreɪt/", pos: "adj.", meaning: "伟大的；极好的" },
  { word: "excellent", phonetic: "/ˈeksələnt/", pos: "adj.", meaning: "极好的；优秀的" },
  { word: "wonderful", phonetic: "/ˈwʌndəfl/", pos: "adj.", meaning: "精彩的" },

  // ── 颜色 ──
  { word: "color", phonetic: "/ˈkʌlə(r)/", pos: "n.", meaning: "颜色" },
  { word: "red", phonetic: "/red/", pos: "adj./n.", meaning: "红色的；红色" },
  { word: "blue", phonetic: "/bluː/", pos: "adj./n.", meaning: "蓝色的；蓝色" },
  { word: "green", phonetic: "/ɡriːn/", pos: "adj./n.", meaning: "绿色的；绿色" },
  { word: "yellow", phonetic: "/ˈjeləʊ/", pos: "adj./n.", meaning: "黄色的；黄色" },
  { word: "black", phonetic: "/blæk/", pos: "adj./n.", meaning: "黑色的；黑色" },
  { word: "white", phonetic: "/waɪt/", pos: "adj./n.", meaning: "白色的；白色" },

  // ── 数字 ──
  { word: "number", phonetic: "/ˈnʌmbə(r)/", pos: "n.", meaning: "数字" },
  { word: "one", phonetic: "/wʌn/", pos: "num.", meaning: "一" },
  { word: "two", phonetic: "/tuː/", pos: "num.", meaning: "二" },
  { word: "three", phonetic: "/θriː/", pos: "num.", meaning: "三" },
  { word: "four", phonetic: "/fɔː(r)/", pos: "num.", meaning: "四" },
  { word: "five", phonetic: "/faɪv/", pos: "num.", meaning: "五" },
  { word: "six", phonetic: "/sɪks/", pos: "num.", meaning: "六" },
  { word: "seven", phonetic: "/ˈsevn/", pos: "num.", meaning: "七" },
  { word: "eight", phonetic: "/eɪt/", pos: "num.", meaning: "八" },
  { word: "nine", phonetic: "/naɪn/", pos: "num.", meaning: "九" },
  { word: "ten", phonetic: "/ten/", pos: "num.", meaning: "十" },
  { word: "hundred", phonetic: "/ˈhʌndrəd/", pos: "num.", meaning: "一百" },
  { word: "thousand", phonetic: "/ˈθaʊznd/", pos: "num.", meaning: "一千" },

  // ── 抽象 / 其他 ──
  { word: "money", phonetic: "/ˈmʌni/", pos: "n.", meaning: "钱" },
  { word: "name", phonetic: "/neɪm/", pos: "n./v.", meaning: "名字；命名" },
  { word: "family", phonetic: "/ˈfæməli/", pos: "n.", meaning: "家庭" },
  { word: "music", phonetic: "/ˈmjuːzɪk/", pos: "n.", meaning: "音乐" },
  { word: "movie", phonetic: "/ˈmuːvi/", pos: "n.", meaning: "电影" },
  { word: "story", phonetic: "/ˈstɔːri/", pos: "n.", meaning: "故事" },
  { word: "dream", phonetic: "/driːm/", pos: "n./v.", meaning: "梦想；做梦" },
  { word: "world", phonetic: "/wɜːld/", pos: "n.", meaning: "世界" },
  { word: "country", phonetic: "/ˈkʌntri/", pos: "n.", meaning: "国家；乡村" },
  { word: "language", phonetic: "/ˈlæŋɡwɪdʒ/", pos: "n.", meaning: "语言" },
  { word: "computer", phonetic: "/kəmˈpjuːtə(r)/", pos: "n.", meaning: "计算机" },
  { word: "phone", phonetic: "/fəʊn/", pos: "n.", meaning: "电话" },
  { word: "picture", phonetic: "/ˈpɪktʃə(r)/", pos: "n.", meaning: "图片；照片" },
  { word: "music", phonetic: "/ˈmjuːzɪk/", pos: "n.", meaning: "音乐" },
  { word: "letter", phonetic: "/ˈletə(r)/", pos: "n.", meaning: "信；字母" },
  { word: "idea", phonetic: "/aɪˈdɪə/", pos: "n.", meaning: "想法；主意" },
  { word: "problem", phonetic: "/ˈprɒbləm/", pos: "n.", meaning: "问题" },
  { word: "game", phonetic: "/ɡeɪm/", pos: "n.", meaning: "游戏" },
  { word: "gift", phonetic: "/ɡɪft/", pos: "n.", meaning: "礼物" },
  { word: "sunny", phonetic: "/ˈsʌni/", pos: "adj.", meaning: "晴朗的" },
  { word: "cloudy", phonetic: "/ˈklaʊdi/", pos: "adj.", meaning: "多云的" },
  { word: "snowy", phonetic: "/ˈsnəʊi/", pos: "adj.", meaning: "下雪的" },
  { word: "rainy", phonetic: "/ˈreɪni/", pos: "adj.", meaning: "下雨的" },
  { word: "spring", phonetic: "/sprɪŋ/", pos: "n.", meaning: "春天" },
  { word: "summer", phonetic: "/ˈsʌmə(r)/", pos: "n.", meaning: "夏天" },
  { word: "autumn", phonetic: "/ˈɔːtəm/", pos: "n.", meaning: "秋天" },
  { word: "winter", phonetic: "/ˈwɪntə(r)/", pos: "n.", meaning: "冬天" },
  { word: "keyboard", phonetic: "/ˈkiːbɔːd/", pos: "n.", meaning: "键盘" },
]

/** 每组练习的单词数量 */
export const SESSION_SIZE = 10

/** Fisher-Yates 洗牌，返回新数组 */
export function shuffle<T>(arr: T[]): T[] {
  const a = [...arr]
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1))
    ;[a[i], a[j]] = [a[j], a[i]]
  }
  return a
}
